### ISSUE TITLE
Add support for Material 3

### ISSUE THREAD

**Issue by wooodenleg** [oleksandrbalan/modalsheet#21]
I use this library for a project that uses Material 3. To achieve the correct theming behaviour, I have to set the sheet background to Transparent and then make my own sheet shape and color.

**Comment by oleksandrbalan** [comment]
There is already official M3 ModalBottomSheet available. 

I would recommend to use that one if possible, or optionally stick with that theming workaround. 

What do you think?

**Comment by wooodenleg** [comment]
Yeah, I've migrated to M3 sheet completely. I hoe they iron all all the bugs soon or I'll have to migrate back :D Closing this for now
