### ISSUE TITLE
Issues with compose preview

### ISSUE THREAD

**Issue by Vaibhav-214** [oleksandrbalan/modalsheet#31]
Really great library just what I was looking for and the demo code was also really helpful but issues with compose preview, when we click on button to open the bottom sheet, it doesnt opens rather the button keeps getting darker where we touch it everytime

**Comment by oleksandrbalan** [comment]
Hi, thx 🤗

ModalSheet is built on FullscreenPopup, which is a lightweight version of Compose Popup and as for now Compose does not support multi-window previews. For example this is a reason why Popup previews also do not work.

I would recommend similar approach as in this SO answer, just extract ModalSheet content to the separate Composable and create a preview for it.

https://stackoverflow.com/a/69681577/14743614
