### ISSUE TITLE
FullscreenPopup 并不是 public 呀

### ISSUE THREAD

**Issue by LZRight123** [oleksandrbalan/modalsheet#38]
<img width="551" alt="image" src="https://github.com/oleksandrbalan/modalsheet/assets/14833970/114839d6-9527-462e-8b48-e423c81f39a4">

**Comment by oleksandrbalan** [comment]
Hi 👋 
Thx for noticing! 
We have intentionally make `FullscreenPopup` internal, but forgot to update a readme.
If you want to use it, feel free to copy-paste it in your project.
