### ISSUE TITLE
[ModalSheet] Observability of sheet state

### ISSUE THREAD

**Issue by wooodenleg** [oleksandrbalan/modalsheet#5]
## Description
Currently there is no way to observe the state of the modal sheet.   

The use case for having this information is for example observing the "hidden" state of the sheet to chain appearance of other UI components like Dialog or even other bottom sheet. Another use case might be to modify/animate the content of the sheet in response to the expanded state. 
Feature request to the material bottom sheet by Colton Idle in Kotlin Slack:
> I have a bottom sheet. When collapsed the padding on top of the text is perfect (according to my designer), but when it's fully expanded, we want to add extra padding so that the text is pushed down. We want the bottom sheet to go all the way up because that's what our designer wants in our edge to edge application.

## Implementation
No thoughts about implementation yet but we could take "inspiration" from Material `ModalBottomSheetState`

**Comment by oleksandrbalan** [comment]
There was an attempt to provide observability via ModalSheetScope in #11, but it feels a bit awkward.

However `ModalSheet` now has an overload which takes `sheetState` and users may use it to observe the state.

**Comment by wooodenleg** [comment]
Closing this for now
